# This is a placeholder so actions won't default to a getting started page

name: kasi-Placeholder

on: push

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
